// lib/presentation/actions/actions_page.dart
//
// Content-only widget for the Recommendations page.
// The sidebar and top bar are provided by AppLayout (via main.dart routes).
//
// Usage (in main.dart):
//   AppLayout(
//     title: 'Recommendations',
//     child: ActionsContent(businessId: '...', businessName: '...', riskId: '...'),
//   )

import 'package:flutter/material.dart';
import 'models/recommendation_model.dart';
import 'services/recommendation_service.dart';
import 'widgets/impact_summary_card.dart';
import 'widgets/recommendation_card.dart';
import 'widgets/stat_chip.dart';

// ── Public widget ─────────────────────────────────────────────────────────────

class ActionsContent extends StatefulWidget {
  final String businessId;
  final String businessName;
  final String riskId;

  const ActionsContent({
    super.key,
    required this.businessId,
    required this.businessName,
    required this.riskId,
  });

  @override
  State<ActionsContent> createState() => _ActionsContentState();
}

class _ActionsContentState extends State<ActionsContent> {
  final RecommendationService _service = RecommendationService();

  List<Recommendation>   _recommendations = [];
  RecommendationSummary? _summary;
  bool    _isLoading    = true;
  bool    _isGenerating = false;
  String? _error;

  // ── Lifecycle ──────────────────────────────────────────────────────────────

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    setState(() { _isLoading = true; _error = null; });
    try {
      final result = await _service.fetchRecommendations(widget.businessId);
      setState(() {
        _summary         = result['summary']         as RecommendationSummary;
        _recommendations = result['recommendations'] as List<Recommendation>;
        _isLoading       = false;
      });
    } catch (err) {
      setState(() { _error = err.toString(); _isLoading = false; });
    }
  }

  Future<void> _onMarkActioned(String id) async {
    try {
      final updated = await _service.markActioned(id);
      setState(() {
        _recommendations = _recommendations
            .map((r) => r.id == id ? updated : r)
            .toList();
      });
    } catch (err) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(SnackBar(
        content:         Text('Failed to update: $err'),
        backgroundColor: Colors.red.shade700,
      ));
    }
  }

  // ── Build ──────────────────────────────────────────────────────────────────

  @override
  Widget build(BuildContext context) {
    // Root is just the content area — AppLayout owns the scaffold/sidebar/topbar
    if (_isLoading) {
      return const Center(child: CircularProgressIndicator());
    }
    if (_error != null) {
      return _buildError();
    }
    return _buildList();
  }

  // ── Error state ────────────────────────────────────────────────────────────

  Widget _buildError() {
    return Center(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(Icons.error_outline, color: Colors.red.shade400, size: 48),
          const SizedBox(height: 12),
          Text(_error!,
              style:     TextStyle(color: Colors.red.shade600),
              textAlign: TextAlign.center),
          const SizedBox(height: 16),
          ElevatedButton.icon(
            onPressed: _load,
            icon:  const Icon(Icons.refresh),
            label: const Text('Retry'),
          ),
        ],
      ),
    );
  }

  // ── List ───────────────────────────────────────────────────────────────────

  Widget _buildList() {
    final topRec = _recommendations.isNotEmpty && !_recommendations.first.isActioned
        ? _recommendations.first
        : null;

    return ListView(
      padding: const EdgeInsets.all(28),
      children: [

        // ── Page header ──────────────────────────────────────────────────────
        Row(children: [
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text(
                  'AI Decision Recommendations',
                  style: TextStyle(
                    fontSize:   26,
                    fontWeight: FontWeight.bold,
                    color:      Color(0xFF0F172A),
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  '${_summary?.totalRecommendations ?? 0} ranked actions generated by '
                  'FinSight AI based on your financial data. Sorted by impact and urgency.',
                  style: const TextStyle(color: Color(0xFF64748B), fontSize: 13),
                ),
              ],
            ),
          ),
          if (_isGenerating)
            const Padding(
              padding: EdgeInsets.only(left: 12),
              child: SizedBox(
                width: 24, height: 24,
                child: CircularProgressIndicator(strokeWidth: 2),
              ),
            ),
        ]),
        const SizedBox(height: 20),

        // ── Impact summary card ──────────────────────────────────────────────
        if (_summary != null)
          ImpactSummaryCard(
            summary:         _summary!,
            recommendations: _recommendations,
          ),
        const SizedBox(height: 16),

        // ── Stat chips ───────────────────────────────────────────────────────
        if (_summary != null)
          Row(children: [
            Expanded(child: StatChip(
              value:   '${_summary!.easyActions}',
              label:   'Easy Actions',
              color:   const Color(0xFF10B981),
              bgColor: const Color(0xFFF0FDF4),
            )),
            const SizedBox(width: 12),
            Expanded(child: StatChip(
              value:   '${_summary!.totalRecommendations}',
              label:   'Total Recommendations',
              color:   const Color(0xFF2563EB),
              bgColor: const Color(0xFFEFF6FF),
            )),
            const SizedBox(width: 12),
            Expanded(child: StatChip(
              value:   '${_summary!.canActToday}',
              label:   'Can Act Today',
              color:   const Color(0xFFF59E0B),
              bgColor: const Color(0xFFFFFBEB),
            )),
          ]),
        const SizedBox(height: 20),

        // ── Highest priority banner ──────────────────────────────────────────
        if (topRec != null) ...[
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
            decoration: const BoxDecoration(
              gradient: LinearGradient(
                colors: [Color(0xFF2563EB), Color(0xFF7C3AED)],
              ),
              borderRadius: BorderRadius.vertical(top: Radius.circular(12)),
            ),
            child: Row(children: const [
              Icon(Icons.star_rounded, color: Color(0xFFFBBF24), size: 18),
              SizedBox(width: 8),
              Text(
                'HIGHEST PRIORITY · RECOMMENDED FIRST ACTION',
                style: TextStyle(
                  color:        Colors.white,
                  fontWeight:   FontWeight.bold,
                  fontSize:     12,
                  letterSpacing: 0.5,
                ),
              ),
            ]),
          ),
          RecommendationCard(
            recommendation: topRec,
            isHighlighted:  true,
            onMarkActioned: () => _onMarkActioned(topRec.id),
          ),
          const SizedBox(height: 16),
        ],

        // ── Remaining recommendations ────────────────────────────────────────
        ..._recommendations
            .skip(topRec != null ? 1 : 0)
            .map((rec) => Padding(
              padding: const EdgeInsets.only(bottom: 12),
              child: RecommendationCard(
                recommendation: rec,
                isHighlighted:  false,
                onMarkActioned: () => _onMarkActioned(rec.id),
              ),
            )),

        // ── Disclaimer ───────────────────────────────────────────────────────
        Container(
          margin:  const EdgeInsets.only(top: 8),
          padding: const EdgeInsets.all(16),
          decoration: BoxDecoration(
            color:        const Color(0xFFFFFBEB),
            borderRadius: BorderRadius.circular(10),
            border:       Border.all(color: const Color(0xFFFDE68A)),
          ),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: const [
              Icon(Icons.lightbulb_outline,
                  color: Color(0xFFD97706), size: 18),
              SizedBox(width: 10),
              Expanded(
                child: Text(
                  'Note: These recommendations are generated by AI based on your '
                  'uploaded financial data and historical patterns. Always consult '
                  'a qualified financial advisor before making significant decisions. '
                  'Impact figures are estimates based on best-case scenarios.',
                  style: TextStyle(color: Color(0xFF92400E), fontSize: 12),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}