// lib/presentation/actions/recommendation_page.dart

import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

// Data layer imports — presentation ONLY calls the repository, never http/mongo
import '../../data/models/recommendation_model.dart';
import '../../data/repositories/recommendation_repository.dart';


class RecommendationPage extends StatefulWidget {
  final String businessId;
  final String businessName;
  final String riskId;

  const RecommendationPage({
    super.key,
    required this.businessId,
    required this.businessName,
    required this.riskId,
  });

  @override
  State<RecommendationPage> createState() => _RecommendationPageState();
}

class _RecommendationPageState extends State<RecommendationPage> {
  // Repository is the ONLY data access point — no raw http here
  final RecommendationRepository _repository = RecommendationRepository();

  List<Recommendation>   _recommendations = [];
  RecommendationSummary? _summary;
  bool    _isLoading    = true;
  bool    _isGenerating = false;
  String? _error;

  
  @override
  void initState() {
    super.initState();
    _loadRecommendations();
  }


  Future<void> _loadRecommendations() async {
    setState(() { _isLoading = true; _error = null; });
    try {
      final result = await _repository.fetchRecommendations(widget.businessId);
      setState(() {
        _summary         = result['summary']         as RecommendationSummary;
        _recommendations = result['recommendations'] as List<Recommendation>;
        _isLoading       = false;
      });
    } catch (err) {
      setState(() { _error = err.toString(); _isLoading = false; });
    }
  }

  Future<void> _onMarkActioned(String id) async {
    try {
      final updated = await _repository.markActioned(id);
      setState(() {
        _recommendations = _recommendations
            .map((r) => r.id == id ? updated : r)
            .toList();
      });
    } catch (err) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(SnackBar(
        content:         Text('Failed to update: $err'),
        backgroundColor: Colors.red.shade700,
      ));
    }
  }

  
  @override
  Widget build(BuildContext context) {
    if (_isLoading) {
      return const Center(child: CircularProgressIndicator());
    }
    if (_error != null) {
      return _buildErrorState();
    }
    return _buildContent();
  }


  Widget _buildErrorState() {
    return Center(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(Icons.error_outline, color: Colors.red.shade400, size: 48),
          const SizedBox(height: 12),
          Text(
            _error!,
            style:     TextStyle(color: Colors.red.shade600),
            textAlign: TextAlign.center,
          ),
          const SizedBox(height: 16),
          ElevatedButton.icon(
            onPressed: _loadRecommendations,
            icon:  const Icon(Icons.refresh),
            label: const Text('Retry'),
          ),
        ],
      ),
    );
  }


  Widget _buildContent() {
    // The highest-priority non-actioned recommendation gets the banner treatment
    final Recommendation? topRec =
        _recommendations.isNotEmpty && !_recommendations.first.isActioned
            ? _recommendations.first
            : null;

    return ListView(
      padding: const EdgeInsets.all(28),
      children: [
        Row(children: [
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text(
                  'AI Decision Recommendations',
                  style: TextStyle(
                    fontSize:   26,
                    fontWeight: FontWeight.bold,
                    color:      Color(0xFF0F172A),
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  '${_summary?.totalRecommendations ?? 0} ranked actions generated by '
                  'FinSight AI based on your financial data. Sorted by impact and urgency.',
                  style: const TextStyle(color: Color(0xFF64748B), fontSize: 13),
                ),
              ],
            ),
          ),
          // Spinner shown during background generation requests
          if (_isGenerating)
            const Padding(
              padding: EdgeInsets.only(left: 12),
              child: SizedBox(
                width: 24, height: 24,
                child: CircularProgressIndicator(strokeWidth: 2),
              ),
            ),
        ]),
        const SizedBox(height: 20),

        if (_summary != null)
          _ImpactSummaryCard(
            summary:         _summary!,
            recommendations: _recommendations,
          ),
        const SizedBox(height: 16),

        // Stat chips 
        if (_summary != null)
          Row(children: [
            Expanded(child: _StatChip(
              value:   '${_summary!.easyActions}',
              label:   'Easy Actions',
              color:   const Color(0xFF10B981),
              bgColor: const Color(0xFFF0FDF4),
            )),
            const SizedBox(width: 12),
            Expanded(child: _StatChip(
              value:   '${_summary!.totalRecommendations}',
              label:   'Total Recommendations',
              color:   const Color(0xFF2563EB),
              bgColor: const Color(0xFFEFF6FF),
            )),
            const SizedBox(width: 12),
            Expanded(child: _StatChip(
              value:   '${_summary!.canActToday}',
              label:   'Can Act Today',
              color:   const Color(0xFFF59E0B),
              bgColor: const Color(0xFFFFFBEB),
            )),
          ]),
        const SizedBox(height: 20),

        // Highest priority banner
        if (topRec != null) ...[
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
            decoration: const BoxDecoration(
              gradient: LinearGradient(
                colors: [Color(0xFF2563EB), Color(0xFF7C3AED)],
              ),
              borderRadius: BorderRadius.vertical(top: Radius.circular(12)),
            ),
            child: Row(children: const [
              Icon(Icons.star_rounded, color: Color(0xFFFBBF24), size: 18),
              SizedBox(width: 8),
              Text(
                'HIGHEST PRIORITY · RECOMMENDED FIRST ACTION',
                style: TextStyle(
                  color:         Colors.white,
                  fontWeight:    FontWeight.bold,
                  fontSize:      12,
                  letterSpacing: 0.5,
                ),
              ),
            ]),
          ),
          _RecommendationCard(
            recommendation: topRec,
            isHighlighted:  true,
            onMarkActioned: () => _onMarkActioned(topRec.id),
          ),
          const SizedBox(height: 16),
        ],

        //Remaining recommendations
        ..._recommendations
            .skip(topRec != null ? 1 : 0)
            .map((rec) => Padding(
              padding: const EdgeInsets.only(bottom: 12),
              child: _RecommendationCard(
                recommendation: rec,
                isHighlighted:  false,
                onMarkActioned: () => _onMarkActioned(rec.id),
              ),
            )),

        //AI disclaimer 
        Container(
          margin:  const EdgeInsets.only(top: 8),
          padding: const EdgeInsets.all(16),
          decoration: BoxDecoration(
            color:        const Color(0xFFFFFBEB),
            borderRadius: BorderRadius.circular(10),
            border:       Border.all(color: const Color(0xFFFDE68A)),
          ),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: const [
              Icon(Icons.lightbulb_outline, color: Color(0xFFD97706), size: 18),
              SizedBox(width: 10),
              Expanded(
                child: Text(
                  'Note: These recommendations are generated by AI based on your '
                  'uploaded financial data and historical patterns. Always consult '
                  'a qualified financial advisor before making significant decisions. '
                  'Impact figures are estimates based on best-case scenarios.',
                  style: TextStyle(color: Color(0xFF92400E), fontSize: 12),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}


class _ImpactSummaryCard extends StatelessWidget {
  final RecommendationSummary summary;
  final List<Recommendation>  recommendations;

  const _ImpactSummaryCard({
    required this.summary,
    required this.recommendations,
  });

  String _rmFormat(double amount) =>
      'RM ${NumberFormat('#,###', 'en_MY').format(amount.round())}';

  Color _barColor(String impactType) {
    switch (impactType) {
      case 'Cash Inflow':         return const Color(0xFF10B981);
      case 'Cash Buffer':         return const Color(0xFFF59E0B);
      case 'Cost Savings':        return const Color(0xFF60A5FA);
      case 'Available Financing': return const Color(0xFF8B5CF6);
      default:                    return const Color(0xFF94A3B8);
    }
  }

  @override
  Widget build(BuildContext context) {
    // Financing is excluded from the bar chart and denominator
    final nonFinancing = recommendations
        .where((r) => r.impactType != 'Available Financing')
        .toList()
      ..sort((a, b) => a.rank.compareTo(b.rank));

    final maxValue = nonFinancing.isEmpty
        ? 1.0
        : nonFinancing.first.projectedImpactValue;

    return Container(
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        color:        const Color(0xFF0F172A),
        borderRadius: BorderRadius.circular(16),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [

          // Header row
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [

              // Left: trophy icon + total impact amount
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text(
                      'TOTAL ACTIONABLE FINANCIAL IMPACT',
                      style: TextStyle(
                        color:         Colors.white54,
                        fontSize:      11,
                        fontWeight:    FontWeight.w600,
                        letterSpacing: 0.8,
                      ),
                    ),
                    const SizedBox(height: 10),
                    Row(children: [
                      Container(
                        width: 42, height: 42,
                        decoration: BoxDecoration(
                          color: Colors.white.withOpacity(0.1),
                          shape: BoxShape.circle,
                        ),
                        child: const Icon(
                          Icons.emoji_events_outlined,
                          color: Color(0xFFFBBF24),
                          size:  22,
                        ),
                      ),
                      const SizedBox(width: 12),
                      Text(
                        '+${_rmFormat(summary.totalActionableImpact)}',
                        style: const TextStyle(
                          color:      Colors.white,
                          fontSize:   30,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ]),
                    const SizedBox(height: 6),
                    Text(
                      'Across ${nonFinancing.length} non-financing recommendations'
                      ' · Excludes SME loan (up to RM 50,000)',
                      style: const TextStyle(color: Colors.white38, fontSize: 11),
                    ),
                  ],
                ),
              ),
              const SizedBox(width: 16),

              // Right: per-type breakdown pills
              Column(
                crossAxisAlignment: CrossAxisAlignment.end,
                children: [
                  if (summary.cashInflow > 0)
                    _buildPill('+${_rmFormat(summary.cashInflow)}',
                        'Invoice Collections', const Color(0xFF10B981)),
                  if (summary.cashBuffer > 0) ...[
                    const SizedBox(height: 8),
                    _buildPill('+${_rmFormat(summary.cashBuffer)}',
                        'Cash Buffer', const Color(0xFFF59E0B)),
                  ],
                  if (summary.costSavings > 0) ...[
                    const SizedBox(height: 8),
                    _buildPill('+${_rmFormat(summary.costSavings)}',
                        'Cost Savings', const Color(0xFF60A5FA)),
                  ],
                ],
              ),
            ],
          ),
          const SizedBox(height: 20),

          // ── Horizontal bar chart ──────────────────────────────────────────
          ...nonFinancing.asMap().entries.map((entry) {
            final idx      = entry.key;
            final rec      = entry.value;
            final fraction = maxValue > 0
                ? (rec.projectedImpactValue / maxValue).clamp(0.0, 1.0)
                : 0.0;

            return Padding(
              padding: const EdgeInsets.only(bottom: 8),
              child: Row(children: [
                SizedBox(
                  width: 28,
                  child: Text('#${idx + 1}',
                      style: const TextStyle(
                          color: Colors.white54, fontSize: 12)),
                ),
                Expanded(
                  child: Stack(children: [
                    Container(
                      height: 8,
                      decoration: BoxDecoration(
                        color:        Colors.white.withOpacity(0.08),
                        borderRadius: BorderRadius.circular(4),
                      ),
                    ),
                    FractionallySizedBox(
                      widthFactor: fraction,
                      child: Container(
                        height: 8,
                        decoration: BoxDecoration(
                          color:        _barColor(rec.impactType),
                          borderRadius: BorderRadius.circular(4),
                        ),
                      ),
                    ),
                  ]),
                ),
                const SizedBox(width: 12),
                SizedBox(
                  width: 80,
                  child: Text(
                    _rmFormat(rec.projectedImpactValue),
                    style: const TextStyle(
                        color: Colors.white70, fontSize: 12),
                    textAlign: TextAlign.right,
                  ),
                ),
              ]),
            );
          }),
        ],
      ),
    );
  }

  Widget _buildPill(String amount, String label, Color color) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
      decoration: BoxDecoration(
        color:        color.withOpacity(0.15),
        borderRadius: BorderRadius.circular(10),
        border:       Border.all(color: color.withOpacity(0.3)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.end,
        children: [
          Text(amount,
              style: TextStyle(
                  color:      color,
                  fontWeight: FontWeight.bold,
                  fontSize:   13)),
          Text(label,
              style: TextStyle(
                  color:    color.withOpacity(0.8),
                  fontSize: 10)),
        ],
      ),
    );
  }
}


class _StatChip extends StatelessWidget {
  final String value;
  final String label;
  final Color  color;
  final Color  bgColor;

  const _StatChip({
    required this.value,
    required this.label,
    required this.color,
    required this.bgColor,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(vertical: 20),
      decoration: BoxDecoration(
        color:        bgColor,
        borderRadius: BorderRadius.circular(12),
        border:       Border.all(color: color.withOpacity(0.2)),
      ),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Text(value,
              style: TextStyle(
                color:      color,
                fontSize:   28,
                fontWeight: FontWeight.bold,
              )),
          const SizedBox(height: 4),
          Text(label,
              style: const TextStyle(
                color:    Color(0xFF64748B),
                fontSize: 12,
              ),
              textAlign: TextAlign.center),
        ],
      ),
    );
  }
}


class _RecommendationCard extends StatefulWidget {
  final Recommendation recommendation;
  final bool           isHighlighted;  // true = priority card (starts expanded)
  final VoidCallback   onMarkActioned;

  const _RecommendationCard({
    required this.recommendation,
    required this.isHighlighted,
    required this.onMarkActioned,
  });

  @override
  State<_RecommendationCard> createState() => _RecommendationCardState();
}

class _RecommendationCardState extends State<_RecommendationCard>
    with SingleTickerProviderStateMixin {
  late bool                _expanded;
  late AnimationController _animController;
  late Animation<double>   _expandAnim;

  @override
  void initState() {
    super.initState();
    _expanded = widget.isHighlighted; // priority card starts open
    _animController = AnimationController(
      vsync:    this,
      duration: const Duration(milliseconds: 260),
      value:    widget.isHighlighted ? 1.0 : 0.0,
    );
    _expandAnim = CurvedAnimation(
        parent: _animController, curve: Curves.easeInOut);
  }

  @override
  void dispose() {
    _animController.dispose();
    super.dispose();
  }

  void _toggle() {
    setState(() => _expanded = !_expanded);
    _expanded ? _animController.forward() : _animController.reverse();
  }

  

  String _rmFormat(double amount) =>
      '+RM ${NumberFormat('#,###', 'en_MY').format(amount.round())}';

  Color _categoryColor(String c) {
    switch (c) {
      case 'Collections':         return const Color(0xFF10B981);
      case 'Supplier Management': return const Color(0xFF6366F1);
      case 'Cost Optimization':   return const Color(0xFFEC4899);
      case 'Financing':           return const Color(0xFF8B5CF6);
      default:                    return const Color(0xFF64748B);
    }
  }

  Color _difficultyColor(String d) {
    switch (d) {
      case 'Easy Action':   return const Color(0xFF10B981);
      case 'Medium Action': return const Color(0xFFF59E0B);
      case 'Hard Action':   return const Color(0xFFEF4444);
      default:              return const Color(0xFF64748B);
    }
  }

  Color _impactColor(String t) {
    switch (t) {
      case 'Cash Inflow':         return const Color(0xFF10B981);
      case 'Cash Buffer':         return const Color(0xFFF59E0B);
      case 'Cost Savings':        return const Color(0xFF3B82F6);
      case 'Available Financing': return const Color(0xFF8B5CF6);
      default:                    return const Color(0xFF64748B);
    }
  }

  IconData _impactIcon(String t) {
    switch (t) {
      case 'Cash Inflow':         return Icons.trending_up;
      case 'Cash Buffer':         return Icons.attach_money;
      case 'Cost Savings':        return Icons.savings_outlined;
      case 'Available Financing': return Icons.account_balance_outlined;
      default:                    return Icons.monetization_on_outlined;
    }
  }

  Color _rankBadgeColor(int rank) {
    switch (rank) {
      case 1:  return const Color(0xFF2563EB);
      case 2:  return const Color(0xFF0F172A);
      case 3:  return const Color(0xFFF59E0B);
      default: return const Color(0xFFE2E8F0);
    }
  }

  
  @override
  Widget build(BuildContext context) {
    final rec         = widget.recommendation;
    final isActioned  = rec.isActioned;
    final impactColor = _impactColor(rec.impactType);

    return Container(
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: widget.isHighlighted
            ? const BorderRadius.vertical(bottom: Radius.circular(12))
            : BorderRadius.circular(12),
        border: Border.all(
          color: isActioned
              ? const Color(0xFF10B981)
              : const Color(0xFFE2E8F0),
        ),
        boxShadow: [
          BoxShadow(
            color:      Colors.black.withOpacity(0.04),
            blurRadius: 8,
            offset:     const Offset(0, 2),
          ),
        ],
      ),
      child: Column(children: [

        
        Padding(
          padding: const EdgeInsets.all(20),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [

              // Rank badge
              Container(
                width: 40, height: 40,
                decoration: BoxDecoration(
                  color: _rankBadgeColor(rec.rank),
                  shape: BoxShape.circle,
                ),
                child: Center(
                  child: Text(
                    '#${rec.rank}',
                    style: TextStyle(
                      color:      rec.rank <= 3 ? Colors.white : const Color(0xFF64748B),
                      fontWeight: FontWeight.bold,
                      fontSize:   13,
                    ),
                  ),
                ),
              ),
              const SizedBox(width: 14),

              // Category tags + title + plan
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Wrap(
                      spacing:    6,
                      runSpacing: 4,
                      children: [
                        _buildTag(rec.category,  _categoryColor(rec.category)),
                        _buildTag(rec.difficulty, _difficultyColor(rec.difficulty),
                            outlined: true),
                        Row(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            const Icon(Icons.access_time,
                                size: 12, color: Color(0xFF64748B)),
                            const SizedBox(width: 4),
                            Text(rec.timeframe,
                                style: const TextStyle(
                                    color: Color(0xFF64748B), fontSize: 12)),
                          ],
                        ),
                      ],
                    ),
                    const SizedBox(height: 8),
                    Text(
                      rec.actionTitle,
                      style: const TextStyle(
                          fontWeight: FontWeight.bold,
                          fontSize:   15,
                          color:      Color(0xFF0F172A)),
                    ),
                    const SizedBox(height: 4),
                    Text(
                      rec.actionPlan,
                      style: const TextStyle(
                          color: Color(0xFF64748B), fontSize: 12),
                    ),
                  ],
                ),
              ),
              const SizedBox(width: 12),

              // Impact pill (projected_impact_value)
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),
                decoration: BoxDecoration(
                  color:        impactColor.withOpacity(0.08),
                  borderRadius: BorderRadius.circular(10),
                  border:       Border.all(color: impactColor.withOpacity(0.2)),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.end,
                  children: [
                    Text(
                      rec.impactType == 'Available Financing'
                          ? 'Up to RM 50,000'
                          : _rmFormat(rec.projectedImpactValue),
                      style: TextStyle(
                        color:      impactColor,
                        fontWeight: FontWeight.bold,
                        fontSize:   15,
                      ),
                    ),
                    const SizedBox(height: 2),
                    Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Icon(_impactIcon(rec.impactType),
                            size: 11, color: impactColor),
                        const SizedBox(width: 3),
                        Text(rec.impactType,
                            style: TextStyle(
                                color:      impactColor,
                                fontSize:   10,
                                fontWeight: FontWeight.w600)),
                      ],
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),

        
        Padding(
          padding: const EdgeInsets.fromLTRB(20, 0, 20, 16),
          child: Row(children: [
            GestureDetector(
              onTap: _toggle,
              child: Row(children: [
                AnimatedRotation(
                  turns:    _expanded ? 0.0 : -0.25,
                  duration: const Duration(milliseconds: 250),
                  child: const Icon(Icons.expand_less,
                      size: 18, color: Color(0xFF2563EB)),
                ),
                const SizedBox(width: 4),
                Text(
                  _expanded ? 'Hide details' : 'View reasoning & steps',
                  style: const TextStyle(
                    color:      Color(0xFF2563EB),
                    fontSize:   13,
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ]),
            ),
            const Spacer(),
            if (isActioned)
              Row(children: const [
                Icon(Icons.check_circle_rounded,
                    color: Color(0xFF10B981), size: 16),
                SizedBox(width: 4),
                Text('Actioned',
                    style: TextStyle(
                        color:      Color(0xFF10B981),
                        fontWeight: FontWeight.w600,
                        fontSize:   13)),
              ])
            else
              ElevatedButton.icon(
                onPressed: widget.onMarkActioned,
                icon:  const Icon(Icons.flash_on, size: 14),
                label: const Text('Mark as Actioned',
                    style: TextStyle(fontSize: 13)),
                style: ElevatedButton.styleFrom(
                  backgroundColor: const Color(0xFF2563EB),
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(
                      horizontal: 14, vertical: 8),
                  shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(8)),
                  elevation: 0,
                ),
              ),
          ]),
        ),

        
        SizeTransition(
          sizeFactor: _expandAnim,
          child: Container(
            margin: const EdgeInsets.fromLTRB(20, 0, 20, 20),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Divider(color: Color(0xFFE2E8F0)),
                const SizedBox(height: 12),

                // AI Reasoning block
                _buildSectionHeader(Icons.radar, 'AI Reasoning'),
                const SizedBox(height: 10),
                Container(
                  padding: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    color:        const Color(0xFFF8FAFC),
                    borderRadius: BorderRadius.circular(8),
                    border:       Border.all(color: const Color(0xFFE2E8F0)),
                  ),
                  child: Text(
                    rec.reasoning,
                    style: const TextStyle(
                        color:    Color(0xFF374151),
                        fontSize: 13,
                        height:   1.6),
                  ),
                ),
                const SizedBox(height: 16),

                // Numbered action steps
                _buildSectionHeader(Icons.check_circle_outline, 'Action Steps'),
                const SizedBox(height: 10),
                ...rec.actionSteps.map((step) => Padding(
                  padding: const EdgeInsets.only(bottom: 8),
                  child: Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Container(
                        width:  24,
                        height: 24,
                        decoration: const BoxDecoration(
                          color: Color(0xFF2563EB),
                          shape: BoxShape.circle,
                        ),
                        child: Center(
                          child: Text(
                            '${step.stepNumber}',
                            style: const TextStyle(
                                color:      Colors.white,
                                fontSize:   11,
                                fontWeight: FontWeight.bold),
                          ),
                        ),
                      ),
                      const SizedBox(width: 10),
                      Expanded(
                        child: Padding(
                          padding: const EdgeInsets.only(top: 3),
                          child: Text(step.description,
                              style: const TextStyle(
                                  color:    Color(0xFF374151),
                                  fontSize: 13)),
                        ),
                      ),
                    ],
                  ),
                )),

                // Related reference badge (e.g. invoice number)
                if (rec.relatedReference != null) ...[
                  const SizedBox(height: 8),
                  Container(
                    padding: const EdgeInsets.symmetric(
                        horizontal: 14, vertical: 10),
                    decoration: BoxDecoration(
                      color:        const Color(0xFFFFFBEB),
                      borderRadius: BorderRadius.circular(8),
                      border:       Border.all(color: const Color(0xFFFDE68A)),
                    ),
                    child: Row(children: [
                      const Icon(Icons.info_outline,
                          color: Color(0xFFD97706), size: 16),
                      const SizedBox(width: 8),
                      Text(
                        'Related reference: ${rec.relatedReference}',
                        style: const TextStyle(
                          color:      Color(0xFF92400E),
                          fontWeight: FontWeight.w600,
                          fontSize:   12,
                        ),
                      ),
                    ]),
                  ),
                ],
              ],
            ),
          ),
        ),
      ]),
    );
  }

  Widget _buildSectionHeader(IconData icon, String label) {
    return Row(children: [
      Icon(icon, color: const Color(0xFF64748B), size: 16),
      const SizedBox(width: 6),
      Text(label,
          style: const TextStyle(
              fontWeight: FontWeight.bold,
              fontSize:   14,
              color:      Color(0xFF0F172A))),
    ]);
  }

  Widget _buildTag(String label, Color color, {bool outlined = false}) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
      decoration: BoxDecoration(
        color:        outlined ? Colors.transparent : color.withOpacity(0.1),
        borderRadius: BorderRadius.circular(6),
        border:       Border.all(
          color: outlined ? color.withOpacity(0.4) : Colors.transparent,
        ),
      ),
      child: Text(label,
          style: TextStyle(
              color:      color,
              fontSize:   11,
              fontWeight: FontWeight.w600)),
    );
  }
}